name: integration-tests
on:
  push:

jobs:
  # Deploys using checkout@v2 with a GITHUB_TOKEN.
  integration-checkout-v2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Build and Deploy
        uses: avdim/github-pages-deploy-action@feature/set_github_pages_info
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: integration
          BASE_BRANCH: dev
          TARGET_FOLDER: docs

      - name: Cleanup Generated Branch
        uses: dawidd6/action-delete-branch@v2.0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branches: gh-pages

